**Pandas**

In [1]:
import numpy as np
import pandas as pd

In [2]:
s=pd.Series([10,20,30,40,50])

In [3]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
s.name="numbers"

In [5]:
s

0    10
1    20
2    30
3    40
4    50
Name: numbers, dtype: int64

In [6]:
#indexing
s[0]

np.int64(10)

In [7]:
s[0:3]

0    10
1    20
2    30
Name: numbers, dtype: int64

In [8]:
#iloc-location based indexing
s.iloc[3]

np.int64(40)

In [11]:
s.iloc[[1,2,4]]

1    20
2    30
4    50
Name: numbers, dtype: int64

In [12]:
index=["apple","banana","grapes","orange","strawberry"]
s.index=index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: numbers, dtype: int64

In [13]:
#error we get from iloc-it is location based indexing,not labelled based,here index is not 0,1,2,3 ,we have apple,banana as index
s.iloc['grapes']

TypeError: Cannot index by location index with a non-integer key

In [14]:
#so loc
s.loc['grapes']

np.int64(30)

In [15]:
s.loc[['grapes','apple']]

grapes    30
apple     10
Name: numbers, dtype: int64

In [16]:
#Series using Dictionaries
fruit_protein={
    "Avocado": 2.0,
    "Banana": 1.3,
    "Kiwi": 1.1,
    "Blackberries": 1.4,
    "Raspberries": 1.2,
    "Guava": 2.6,
    "Jackfruit": 1.5,
    "Durian": 1.5,
    "Pomegranate": 1.7,
    "Passion Fruit": 2.2
}
s2=pd.Series(fruit_protein)
s2

Avocado          2.0
Banana           1.3
Kiwi             1.1
Blackberries     1.4
Raspberries      1.2
Guava            2.6
Jackfruit        1.5
Durian           1.5
Pomegranate      1.7
Passion Fruit    2.2
dtype: float64

In [17]:
s2.name="Calories"

In [18]:
s2

Avocado          2.0
Banana           1.3
Kiwi             1.1
Blackberries     1.4
Raspberries      1.2
Guava            2.6
Jackfruit        1.5
Durian           1.5
Pomegranate      1.7
Passion Fruit    2.2
Name: Calories, dtype: float64

In [19]:
#Condition Selection
s2>1

Avocado          True
Banana           True
Kiwi             True
Blackberries     True
Raspberries      True
Guava            True
Jackfruit        True
Durian           True
Pomegranate      True
Passion Fruit    True
Name: Calories, dtype: bool

In [20]:
s2[s2>1]

Avocado          2.0
Banana           1.3
Kiwi             1.1
Blackberries     1.4
Raspberries      1.2
Guava            2.6
Jackfruit        1.5
Durian           1.5
Pomegranate      1.7
Passion Fruit    2.2
Name: Calories, dtype: float64

In [21]:
#Logical Operators
s2[(s2>0.5)&(s2<2)]

Banana          1.3
Kiwi            1.1
Blackberries    1.4
Raspberries     1.2
Jackfruit       1.5
Durian          1.5
Pomegranate     1.7
Name: Calories, dtype: float64

In [22]:
s2[(s2>0.5)|(s2<2)]

Avocado          2.0
Banana           1.3
Kiwi             1.1
Blackberries     1.4
Raspberries      1.2
Guava            2.6
Jackfruit        1.5
Durian           1.5
Pomegranate      1.7
Passion Fruit    2.2
Name: Calories, dtype: float64

In [25]:
s2[~(s2<1.5)]

Avocado          2.0
Guava            2.6
Jackfruit        1.5
Durian           1.5
Pomegranate      1.7
Passion Fruit    2.2
Name: Calories, dtype: float64

In [26]:
#Modifiying
s2["Guava"]=3.0

In [27]:
s2

Avocado          2.0
Banana           1.3
Kiwi             1.1
Blackberries     1.4
Raspberries      1.2
Guava            3.0
Jackfruit        1.5
Durian           1.5
Pomegranate      1.7
Passion Fruit    2.2
Name: Calories, dtype: float64

In [28]:
#Dataframes
data={
    "Name":["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace"],
    "Age":[25, 30, np.nan, 35, 40, 28, np.nan],
    "Department":["HR", "IT", "Finance", np.nan, "Marketing", "HR", "IT"],
    "Salary":[50000.0, 60000.0, np.nan, 80000.0, 70000.0, 55000.0, 62000.0]
}
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie   NaN    Finance      NaN
3    David  35.0        NaN  80000.0
4      Eve  40.0  Marketing  70000.0
5    Frank  28.0         HR  55000.0
6    Grace   NaN         IT  62000.0

In [29]:
df.iloc[1:3]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie   NaN    Finance      NaN

In [30]:
df.loc[1:3,["Age","Department"]]

    Age Department
1  30.0         IT
2   NaN    Finance
3  35.0        NaN

In [31]:
#Drop Columns
df.drop("Age",axis=1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance      NaN
3    David        NaN  80000.0
4      Eve  Marketing  70000.0
5    Frank         HR  55000.0
6    Grace         IT  62000.0

In [32]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie   NaN    Finance      NaN
3    David  35.0        NaN  80000.0
4      Eve  40.0  Marketing  70000.0
5    Frank  28.0         HR  55000.0
6    Grace   NaN         IT  62000.0

In [33]:
df.drop("Age",axis=1,inplace=True)

In [34]:
df

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance      NaN
3    David        NaN  80000.0
4      Eve  Marketing  70000.0
5    Frank         HR  55000.0
6    Grace         IT  62000.0

In [35]:
df.shape

(7, 3)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        7 non-null      object
 1   Department  6 non-null      object
 2   Salary      6 non-null      float64
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [37]:
df.describe()

             Salary
count      6.000000
mean   62833.333333
std    10778.064143
min    50000.000000
25%    56250.000000
50%    61000.000000
75%    68000.000000
max    80000.000000

In [38]:
#Broadcasting
df['Salary']=df["Salary"]+5000
df['Salary']

0    55000.0
1    65000.0
2        NaN
3    85000.0
4    75000.0
5    60000.0
6    67000.0
Name: Salary, dtype: float64

In [39]:
#renaming columns
df.rename(columns={"Department":"Dept"},inplace=True)

In [40]:
df

      Name       Dept   Salary
0    Alice         HR  55000.0
1      Bob         IT  65000.0
2  Charlie    Finance      NaN
3    David        NaN  85000.0
4      Eve  Marketing  75000.0
5    Frank         HR  60000.0
6    Grace         IT  67000.0

In [41]:
#Unique values
df["Dept"].unique()

array(['HR', 'IT', 'Finance', nan, 'Marketing'], dtype=object)

In [42]:
#value_counts
df["Dept"].value_counts()

Dept
HR           2
IT           2
Finance      1
Marketing    1
Name: count, dtype: int64

In [43]:
#Add new column
df["Promoted Salary"]=df["Salary"]*10

In [44]:
df

      Name       Dept   Salary  Promoted Salary
0    Alice         HR  55000.0         550000.0
1      Bob         IT  65000.0         650000.0
2  Charlie    Finance      NaN              NaN
3    David        NaN  85000.0         850000.0
4      Eve  Marketing  75000.0         750000.0
5    Frank         HR  60000.0         600000.0
6    Grace         IT  67000.0         670000.0

In [45]:
#Data Cleaning
df.isnull()

    Name   Dept  Salary  Promoted Salary
0  False  False   False            False
1  False  False   False            False
2  False  False    True             True
3  False   True   False            False
4  False  False   False            False
5  False  False   False            False
6  False  False   False            False

In [46]:
df.isnull().sum()

Name               0
Dept               1
Salary             1
Promoted Salary    1
dtype: int64

In [47]:
#drop null values
df.dropna()

    Name       Dept   Salary  Promoted Salary
0  Alice         HR  55000.0         550000.0
1    Bob         IT  65000.0         650000.0
4    Eve  Marketing  75000.0         750000.0
5  Frank         HR  60000.0         600000.0
6  Grace         IT  67000.0         670000.0

In [48]:
df.dropna(how="any")

    Name       Dept   Salary  Promoted Salary
0  Alice         HR  55000.0         550000.0
1    Bob         IT  65000.0         650000.0
4    Eve  Marketing  75000.0         750000.0
5  Frank         HR  60000.0         600000.0
6  Grace         IT  67000.0         670000.0

In [49]:
df.dropna(how="all")

      Name       Dept   Salary  Promoted Salary
0    Alice         HR  55000.0         550000.0
1      Bob         IT  65000.0         650000.0
2  Charlie    Finance      NaN              NaN
3    David        NaN  85000.0         850000.0
4      Eve  Marketing  75000.0         750000.0
5    Frank         HR  60000.0         600000.0
6    Grace         IT  67000.0         670000.0

In [50]:
#fill the null values
df.fillna(0)

      Name       Dept   Salary  Promoted Salary
0    Alice         HR  55000.0         550000.0
1      Bob         IT  65000.0         650000.0
2  Charlie    Finance      0.0              0.0
3    David          0  85000.0         850000.0
4      Eve  Marketing  75000.0         750000.0
5    Frank         HR  60000.0         600000.0
6    Grace         IT  67000.0         670000.0

In [52]:
df["Salary"].fillna(df["Salary"].mean())

0    55000.000000
1    65000.000000
2    67833.333333
3    85000.000000
4    75000.000000
5    60000.000000
6    67000.000000
Name: Salary, dtype: float64

In [53]:
#forward fill
df["Dept"].fillna(method="ffill")

/tmp/ipykernel_1403/3200471382.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Dept"].fillna(method="ffill")

0           HR
1           IT
2      Finance
3      Finance
4    Marketing
5           HR
6           IT
Name: Dept, dtype: object

In [54]:
#backward fill
df["Dept"].fillna(method="bfill")

/tmp/ipykernel_1403/879159452.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Dept"].fillna(method="bfill")

0           HR
1           IT
2      Finance
3    Marketing
4    Marketing
5           HR
6           IT
Name: Dept, dtype: object

In [55]:
#replace
df["Name"].replace("Alice","Rose")

0       Rose
1        Bob
2    Charlie
3      David
4        Eve
5      Frank
6      Grace
Name: Name, dtype: object

In [56]:
#Duplicates
df_dup=df[df.duplicated()]
df_dup

Empty DataFrame
Columns: [Name, Dept, Salary, Promoted Salary]
Index: []

In [57]:
#drop duplicates
df=df.drop_duplicates()

In [63]:
#invalid values
df['Promoted Salary']=df['Promoted Salary'].apply(lambda x: x/10 if x>6000 else x)

In [64]:
df['Promoted Salary']

0    5500.0
1    6500.0
2       NaN
3     850.0
4     750.0
5    6000.0
6     670.0
Name: Promoted Salary, dtype: float64

In [60]:
df

      Name       Dept   Salary  Promoted Salary
0    Alice         HR  55000.0          55000.0
1      Bob         IT  65000.0          65000.0
2  Charlie    Finance      NaN              NaN
3    David        NaN  85000.0          85000.0
4      Eve  Marketing  75000.0          75000.0
5    Frank         HR  60000.0          60000.0
6    Grace         IT  67000.0          67000.0

In [66]:
#Joins and merge
department_info={
    "Department":["HR","IT","Finance","Marketing"],
    "Location":["New York","San Francisco","Los Angeles","Chicago"],
    "Manager":["Alice","Bob","Charlie","David"]
}

In [67]:
df2=pd.DataFrame(department_info)
df2

  Department       Location  Manager
0         HR       New York    Alice
1         IT  San Francisco      Bob
2    Finance    Los Angeles  Charlie
3  Marketing        Chicago    David

In [68]:
#Merge two datasets
pd.concat([df,df2])

,Name,Dept,Salary,Promoted Salary,Department,Location,Manager
0,Alice,HR,55000.0,5500.0,NaN,NaN,NaN
1,Bob,IT,65000.0,6500.0,NaN,NaN,NaN
2,Charlie,Finance,NaN,NaN,NaN,NaN,NaN
3,David,NaN,85000.0,850.0,NaN,NaN,NaN
4,Eve,Marketing,75000.0,750.0,NaN,NaN,NaN
5,Frank,HR,60000.0,6000.0,NaN,NaN,NaN
6,Grace,IT,67000.0,670.0,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,HR,New York,Alice
1,NaN,NaN,NaN,NaN,IT,San Francisco,Bob
2,NaN,NaN,NaN,NaN,Finance,Los Angeles,Charlie
3,NaN,NaN,NaN,NaN,Marketing,Chicago,David

In [70]:
#column wise
pd.concat([df,df2],axis=1)

,Name,Dept,Salary,Promoted Salary,Department,Location,Manager
0,Alice,HR,55000.0,5500.0,HR,New York,Alice
1,Bob,IT,65000.0,6500.0,IT,San Francisco,Bob
2,Charlie,Finance,NaN,NaN,Finance,Los Angeles,Charlie
3,David,NaN,85000.0,850.0,Marketing,Chicago,David
4,Eve,Marketing,75000.0,750.0,NaN,NaN,NaN
5,Frank,HR,60000.0,6000.0,NaN,NaN,NaN
6,Grace,IT,67000.0,670.0,NaN,NaN,NaN

In [74]:
pd.merge(df, df2, left_on="Dept", right_on="Department")

,Name,Dept,Salary,Promoted Salary,Department,Location,Manager
0,Alice,HR,55000.0,5500.0,HR,New York,Alice
1,Bob,IT,65000.0,6500.0,IT,San Francisco,Bob
2,Charlie,Finance,NaN,NaN,Finance,Los Angeles,Charlie
3,Eve,Marketing,75000.0,750.0,Marketing,Chicago,David
4,Frank,HR,60000.0,6000.0,HR,New York,Alice
5,Grace,IT,67000.0,670.0,IT,San Francisco,Bob

In [ ]:
#importing files
data=pd.read_csv("path")